hyp:
  num_epochs: 3
  batch_size: 32
  learning_rate: 0.001
  num_workers: 0

model:
  type: yolov5 # yolov8 | yolov5 | retinanet | detr
  pretrained: true
  num_classes: 7

data_path: data/raw/vogelbacher23
show_progress: true
